### ISSUE TITLE
Q 22, option identifier "c" is doubled

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#122]

**Comment by gernotstarke** [comment]
that had been fixed in some commit, but the version id wasn't upgraded

**Comment by programming-wolf** [comment]
I do not see question 22 changed in any commit over the last 1.5 years.

**Comment by programming-wolf** [comment]
Ah, I found it: It was a PR from a generous author. 
50bdd8734e57c601e70965778818ada0d78b254b

I will update the version number after my changes today.
