### ISSUE TITLE
Possible Points adds up to 51, exam says only 50 should be possible

### ISSUE THREAD

**Issue by reggiemouse** [isaqb-org/examination-foundation#125]
There are twelve 2 point questions:  3,4,10,11,14,26,27,28,32,34,37,38

The exam description at the beginning states only 50 points should be possible.

**Comment by gernotstarke** [comment]
oops - we'll crosscheck in the different language versions and will fix that
(no date promised)

**Comment by gernotstarke** [comment]
fixed in 2023.1
