### ISSUE TITLE
Q-25 (Q-20-04-21) - (c) point is confusing

### ISSUE THREAD

**Issue by izaruba** [isaqb-org/examination-foundation#16]
According to the answer sheet, (c) option "Building blocks use a common database" is considered to be a characteristic of tight coupling.

That seems a bit confusing since using a common database does not always mean using the same table, stored procedure, or any other shared object within a database.

The tight coupling would exist when "Building blocks **communicate** using a common database" or "Building blocks **use a common object** within a database", but there's no hint in the text to make it rather clear.

**Comment by gernotstarke** [comment]
@izaruba - thank you very much for your comment!

You're right, of course. Imho we had the implicit assumption that "common database" means "a common table/object/stored-proc/schema/..." within that database.  

We will rephrase that distractor to reflect your comment!!

@iSAQB-GmbH - not sure WHEN this change will be done, but it should then be reflected in translations...

**Comment by gernotstarke** [comment]
fixed, "use common table with a relational database"
