### ISSUE TITLE
Question 39: Double "negotiation", inconsistency and singular form

### ISSUE THREAD

**Issue by malliaridis** [isaqb-org/examination-foundation#17]
In *Question 39* the question asks for the alternatives that **cannot** be measured. By requesting to pick "the least likely" alternatives the examinee might look for the answer that does at **least** answer the question correctly. By saying there are "least likely" answers you also mean there is no absolute wrong answer, "cannot" however expresses an absolute wrong answer.

Full question:
"Which of the following alternative cannot be measured in your software architecture? Pick the TWO answers that are least likely."

Suggestion:
"Which of the following alternative**s are harder to measure** in your software architecture? Pick TWO answers."

**Comment by gernotstarke** [comment]
Thank you Christos, for both outlining the problem and proposing a solution.

We'll definitely update this question asap.

**Comment by gernotstarke** [comment]
fixed (by following your suggestion, @malliaridis )
