### ISSUE TITLE
Erklärung zu K-Fragen in "Examination-Rules-de.pdf" fehlerhaft

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#18]
<img width="885" alt="Screenshot 2020-10-22 um 18 52 12" src="https://user-images.githubusercontent.com/1233990/96904924-0e27b580-1498-11eb-942b-2d6b3ee9cbd7.png">

Fehler gefunden von M.Ploed - in der umkreisten Variante fehlt ein Kreuz...

**Comment by gernotstarke** [comment]
d.h. SO wie es da steht gibt es für diese Variante Null Punkte (einKreuz falsch, eines richtig, eines ausgelassen)

**Comment by alxlo** [comment]
Ja, da fehlt unten links das Kreuz. Das ist aber mal eine interessante Regression. Das war jahrelang korrekt :-/

**Comment by gernotstarke** [comment]
fixed, bumped up DE version to 2020.2
