### ISSUE TITLE
Q-20-04-26 suboptimal answer item b

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#22]
@alxlo opened this:

Question 33
There is a good chance for misinterpretation of item b). I can understand from a purely practical point of view that not all design decisions get written down.

On the other hand, that's what "should" be done: Making design decisions explicit. This answer only becomes false, because trivial design decision, which are the ones we do not need to think about, the "no-brainers", which are hardly design decisions at all but rather employment of best practices do not have to be written down.

Therefore this is just "nitpicking" about the word "all" and the answer in a broader context even opposes what we teach about making design decision explicit. IMHO this is only a "real without discussion false" if the statement were "Software architects must justify all design decisions in writing"

Options

**Comment by gernotstarke** [comment]
@Hruschka commented:

We had that discussion. But we decided that "Must" is too strong. "should"  is still strong enough to make the answer false. You do hundreds of design decisions in a project and you should definitely (even in theory) NOT explain all of them in writing. Think about deciding to have 3 parameters instead of 2. Think about changing a method name to a better one. Think about moving a class to a different package, and so on.

Yes: Explicit, not implicit is the recommandation, but "ALL" in an answer is nearly ALWAYS wrong.

Peter

**Comment by gernotstarke** [comment]
@ulibecker I agree with Peter Hruschka, writing down all design decisions is clearly wrong

**Comment by gernotstarke** [comment]
I second Peter and Uli... everything in writing is clearly wrong in many cases

**Comment by rhoadesre** [comment]
I'm with Alexander. I think it's confusing to combine "should" with "all". I suggest either changing "should" to "must" so that it's clear, or make it a correct answer with something like "Software Architects should justify all significant architecture decisions in writing".

**Comment by rhoadesre** [comment]
P.S. the English version of "decision" should be plural: "all design decision**_s_**"

**Comment by rhoadesre** [comment]
Compromise: "shall" instead of "should" is at least clearer
