### ISSUE TITLE
migrate mock-questions to asciidoc from docx

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#23]
the change history of binary documents is impossible to track - which makes it really hard for trainers to
follow changes

(numerous trainers have converted the docx into their own formats (i.e. google forms, confluence etc) - and would like
to incorporate the changes we perform on the official version of the questions. Not possible with docx, a breeze with asciidoc.

**Comment by gernotstarke** [comment]
Therefore I (strongly) propose we take our established toolchain (gradle build, github actions, pdf-template) and migrate...
(I start that migration on a branch, as we need to establish a standardized format for the three question types.

Furthermore we need to consider automatically creating the answer-sheet (the current two-docx-document-approach is error-prone)

**Comment by gernotstarke** [comment]
another approach would be the xml-based toolchain from the real examination - but the xslt processiong really makes me afraid... and xml is not my personal favorite...

**Comment by alxlo** [comment]
I'm very in favor of reworking the existing tool chain, there is only a little bit of black magic inside and the combination of XSLT+XSL-FO is quite fun to work with. (OK, sometimes also quite "fun").

**Comment by gernotstarke** [comment]
Sorry @alxlo  - @programming-wolf and myself were faster and completely migrated to an asciidoc version of the mock exam. The output looks awesome (imho) - and now we have a text-based version, with q+a in a single source :-)
