### ISSUE TITLE
Q-12: Product Family/-suite is not part of curriculum and therefore questionable

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#25]
the term "product family" is overly vague...

**Comment by gernotstarke** [comment]
product line engineering is NOT part of FOUNDATION, question should be replaced!!

**Comment by gernotstarke** [comment]
please comment! I suggest to remove this question!!

**Comment by programming-wolf** [comment]
I'd say: remove it. I do not think that you can answer this properly, because the answers might be different for different products/companies.

**Comment by gernotstarke** [comment]
removed in 2021.1-DE-rev3

**Comment by gernotstarke** [comment]
EN version needs to be updated too

**Comment by rhoadesre** [comment]
From my perspective, it can be removed. If it's kept, I have a few suggestions to make the answers more consistent.

**Comment by rhoadesre** [comment]
Are the mock exams maintained here as word documents? 
https://github.com/isaqb-org/examination-foundation/tree/master/raw/mock_exam

**Comment by programming-wolf** [comment]
Yes, until I've got time to move them to asciidoc.

**Comment by alxlo** [comment]
> Yes, until I've got time to move them to asciidoc.

I'd rather we move them to the XML based toolchain we use for the real questions. This does not come out of a whim but Gernot and I have talked quite a lot about this and everyone came full circle that asciidoc is not a good idea in the end. Let's discuss that with Gernot when we find time.
