### ISSUE TITLE
Q-7, option (e), Information-Hiding auf Klassenebene

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#31]
we should not make assumptions about technical details of programming languages.

In java, for example, there is no other information-hiding construct that on class level (unless Jigsaw is considered),
and OO in JavaScript, Scala and Golang or Python is different...

Suggestion: remove option (e)

**Comment by Hruschka** [comment]
Agreed. Drop Option e.

**Comment by rhoadesre** [comment]
Agreed

**Comment by alxlo** [comment]
Shouldn't we point out that different programming languages have a very varying degree of built-in support for archtecture rules? Of course we *can* strive to eliminate technical and/or implementation details. What I am afraid of here is that we end up with a very anemic view of software architecture that is so far from implementation that our students will have difficulties putting it into practice.

**Comment by gernotstarke** [comment]
@alxlo that would be a different (and imho interesting) question - but currently option (e) is disturbing (marked as "wrong" in the answer sheet, but "correct" from at least a Java or C# point of view.

**Comment by gernotstarke** [comment]
done

**Comment by gernotstarke** [comment]
removed (e), reduced to 1Point
