### ISSUE TITLE
Mock Q2: Database schemata and Hardware Sizing should / could be part of software architecture

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#32]
I think both database schemata and hardware sizing are part of software architecture.

I think you could argue either way, if a database scheme should be created as part of the software architecture. I've had projects where I created them and others where the development team created the database schema. 

I've performed hardware sizing for every architecture I've worked on. The operations / admin department needs this information to order / configure the correct hardware.

**Comment by alxlo** [comment]
It's a P-Question. Not checking answers does **not** mean that they do not apply at all.

By the way the "P-Question: Choose the three best aspects." in the question header does not fit the uniform template we have on real questions. That part varies a lot throughout the exam here. See #44 .

**Comment by gernotstarke** [comment]
in P-questions, it's NOT about picking everything that might be correct, but picking the best x options.

**Comment by gernotstarke** [comment]
great question to illustrate the working of P-questions...

**Comment by alxlo** [comment]
I'm very in favour of **not** "overfitting" the questions. Having questions in the mock exam that are not super precise helps to prepare students for "less perfect" questions in the real exam (that shouldn't be there, but might creep in).

**Comment by rhoadesre** [comment]
I would not be able to pick the "best" three answers. The P-question works if everyone agrees what the three "best" answers are.

**Comment by gernotstarke** [comment]
I can imagine situations where DB-schema are more important than other crosscutting concepts... therefore I suggest to replace this distractor by something different.

What about

(d) Coding conventions

**Comment by gernotstarke** [comment]
replaced (d) by coding conventions to clarify.

@alxlo I hope this will NOT be "overfitting", but clarify the question...
