### ISSUE TITLE
Mock Q3: Answer G is confusing (a concept might be implemented by a single building block)

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#34]
Answer G is confusing (a concept might be implemented by a single building block). Cross-cutting concerns are called cross-cutting because they can't be completely implemented by a single building block. E.g. there may be a central logging server, but there is still logging code all over the system. 

Suggestion: Remove answer G or use a similar answer that is used in the exam.

**Comment by alxlo** [comment]
No no no no. That is how you want to do it. You have one logging component and annotations on all the things you want to log. Logging is implemented by a single building block an not strewn all over the place.

**Comment by rhoadesre** [comment]
The central logging component and the annotations will help reduce the redundant code, but logging code will still be spread throughout the system.

**Comment by gernotstarke** [comment]
GS and RR could not agree upon a change...

**Comment by gernotstarke** [comment]
but agreed to close this issue...
