### ISSUE TITLE
Mock Q9: Answers not definite

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#36]
Answers A and D: 

In both cases, these are best practices (nice-toh-haves), but not requirements (must). This is dependent on the requirements and their priorities. Making the architecture flexible to react to changes in business processes or technologies without requiring a lot of changes is a good idea, but requires effort and time (= money). This must be prioritized by the customer as a "maintainability" or "adaptability" requirement. 

It's also important to recognize where the architecture should be flexible, and not simply make a blanket statement. I.e. if the business processes or technologies rarely or never change, then don't spend a lot time making the architecture flexible.

Recommendation:
Combine the answers and simplify. E.g.:
"You should work with the stakeholders to determine where the requirements and constraints will change often (e.g. business processes, technologies), and design the architecture such that changes can occur without requiring extensive restructuring of the software architecture."

**Comment by gernotstarke** [comment]
removed option (d), slightly rephrased question
