### ISSUE TITLE
Mock Q9: Infrastructure independence

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#37]
Answer C: 
I'm not sure what this answer is trying to convey and it's confusing. In general, I believe:
1) The software architecture should specify the requirements on the hardware or infrastructure.
2) You need to work with operations together. Completely specifying the architecture before talking with operations doesn't work well.

Answer C Recommendation (for an answer that is (hopefully) clearly false. Even with virtualization, you can't be completely independent of the infrastructure:
"The software architecture can designed to be completely independent of the hardware and infrastructure"

**Comment by gernotstarke** [comment]
+1, current option (c) is completely misleading

changed to "Die Softwarearchitektur kann so gestaltet werden, dass sie völlig unabhängig von der Hardware und Infrastruktur ist"
