### ISSUE TITLE
Mock Q10: Testing

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#38]
Answer A: "Help the business people to express quality requirements in a way that can be tested."

Is it really our responsibility to ensure that quality requirements are specified in a way that they can be tested? 

Recommendation: 
"Help the business people to express quality requirements in a way that can be implemented."

This is redundant to answer E ("Check requirements for technological feasibility"), but I think that's OK.

**Comment by gernotstarke** [comment]
slightly changed (a)
