### ISSUE TITLE
Mock Q19: Better formulation

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#40]
Original question: 
"You document a component of your software architecture. Which information should be contained in your black box description and which information should be avoided?"

Recommendation for the question:
"When documenting a building block of your software architecture, which information should be contained in the black-box description and which information should be avoided?"

Original answers:
a) Interfaces
b) Responsibility
c) Internal structure
d) Hints for the implementation

Recommended answers:
a) Interfaces to external building blocks
b) Responsibility of the building block
c) Internal structure of the building block
d) Specification of the implementation details

**Comment by gernotstarke** [comment]
changed some options in DE and EN
