### ISSUE TITLE
Enforce uniform standard instructions for each question type.

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/examination-foundation#44]
In the real exam there are uniform standard instructions that are generated depending on the question type:
- A-Question: Choose one answer.
- P-Question: From the following $n answers select $k that fit best.
- K-Question: Assign all answers.

The mock exam provides a wild rainbow of variations here (not good):
- P-Question: Choose the $n best aspects.
- P-Question: Choose the $n best options.
- P-Question: Choose the $n best answers.
- P-Question: Choose the $n best-fitting answers.
- P-Question: Choose the $n most important responsibilities.
- P-Question: Choose the $n most important action items.
- P-Question: Choose the $n most often found in practice.

**Comment by programming-wolf** [comment]
What are the correct German terms, @alxlo ?

**Comment by alxlo** [comment]
@programming-wolf Here they are:
- A-Frage: Bitte kreuzen Sie die richtige Antwort an.
- P-Frage: Wählen Sie aus den folgenden $n Antworten die $k Antworten aus, die am besten passen.
- K-Frage: Bitte ordnen Sie jede Antwort einer Kategorie zu.
