### ISSUE TITLE
Mock Q32: One answer needs clarification

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#47]
For this issue, I don't have a recommended answer.

Original answer b: "The client code should be easy to understand." 

Problem: We're not necessarily responsible for creating the client code and have no control over the understandability. In addition, if it's a functionally complicated interface, it may not be easy to create a small, understandable client.

**Comment by gernotstarke** [comment]
changed DE (b) to  "Client-Code sollte angemessen leicht zu verstehen sein."
