### ISSUE TITLE
Mock Q32: content and small English changes for answer C

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#48]
Original answer c: 
"An interface should be defined by the provider of the appropriate service"

Recommended answer c: 
"An interface should be defined from the perspective of the provider of the corresponding service"

**Comment by gernotstarke** [comment]
option (c) is marked "wrong" - (which is not obvious from my viewpoint)... let's find another distractor

**Comment by gernotstarke** [comment]
changed (c) to more distracting distractor (Eine Schnittstelle soll Zugriff auf eine umfassende Menge
von Implementierungsdetails ermöglichen),
added new distractor (e)
