### ISSUE TITLE
Mock Q33: clarification of answers

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#49]
**Original answers:**
a) Architectural decisions can implicitly be contained in the structure of the building block/component view.
b) Software architects should justify all design decision in writing
c) ...
d) ...

**Problems:**
a) confusing
b) this is marked as incorrect, but I would say, at least for the main decisions, they should be documented. If you said, absolutely every single small decision should be documented, this takes it to the extreme. I prefer to document even small decisions, but it's obviously not possible to document every single decision (some of which aren't even conscious decisions).

**Recommended answers:**
a) Architectural decisions can implicitly or explicitly impact the structure of the building blocks / components.
b) [option 1: change to correct answer (my preference)] Software architects should justify all major design decisions in writing.
b) [option 2: leave as incorrect answer] The justification for architecture decisions does not need to be documented since it is not relevant to the implementers of the architecture. They only need to know what should be implemented and how.
c) ...
d) ...

**Comment by gernotstarke** [comment]
(b) still under discussion, (a) modified

**Comment by gernotstarke** [comment]
RR + GS could not agree upon improvement of (b)
