### ISSUE TITLE
Mock 34: Content and English changes

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#50]
In the first place, all answers are true. How about adding a distractor? Refer to recommended answers.

**Original question:**
Which of the following statements is a good reason for maintaining (adequate) architecture documentation and which is no good reason?

**Recommended question:**
Which of the following are typical reasons for maintaining (adequate) architecture documentation?
[The heading for the categories would be "typical" and "atypical"]

**Original answer a:**
a) To enable onboarding of new developers.
[you don't fully enable, but support, expedite etc.]

**Recommended answer a:**
a) To expedite onboarding of new developers.

**Possible distractors**
e) Ensure that developers have enough work to do.
f) Automate the testing approach of the architecture

**Comment by gernotstarke** [comment]
done in DE and EN, added Distractors, changed to 2 points
