### ISSUE TITLE
Mock Q38: English or maybe clarity

### ISSUE THREAD

**Issue by rhoadesre** [isaqb-org/examination-foundation#53]
**Original answer b:**
b) Inappropriate names of public methods.

**Problem:**
1) Not really clear. What is "ungeeignet" / "unsuitable", " inappropriate", or "improper". According to who or what?
2) Inappropriate could imply not "offensive"

**Recommendation:**
b) public methods that don't accurately reflect the intended functionality

**Comment by gernotstarke** [comment]
changed to (by RR+GS)

DE: Namen öffentlicher Methoden geben nicht deren Zweck wieder
EN: Names of public methods do not reflect their purpose
