### ISSUE TITLE
Q-17-13-02 Incorrect German translation for (a)

### ISSUE THREAD

**Issue by Pharb** [isaqb-org/examination-foundation#54]
_English_: "The chief architect coordinates the creation of the documentation."
_German_: "Der leitende Architekt erstellt die Dokumentation."

Source: https://github.com/isaqb-org/examination-foundation/blob/master/docs/mock_exam/Mock-Exam-Fragen-DE.pdf

The translation changes the meaning of the sentence, leading to confusion with the given answers.

A correct translation could be: "Der leitende Architekt koordiniert die Erstellung der Dokumentation."

**Comment by gernotstarke** [comment]
was already fixed in rev3 - maybe in our (partially manual) upload process something failed.

the DE version of the "raw" document already contained the correct translation.

I updated the gendering of the question (in DE) and exported new pdfs - leading to rev4.

@Pharb - please verify

**Comment by Pharb** [comment]
Thanks for updating the PDF, looks good to me 👍
