### ISSUE TITLE
Q-20-04-14 Incorrect German translation for (d)

### ISSUE THREAD

**Issue by Pharb** [isaqb-org/examination-foundation#55]
_English_: "Adherence to DRY leads to additional attack vectors in IT security."
_German_: "Die Einhaltung von DRY führt zu einer Verringerung der Angriffsvektoren in der IT-Sicherheit."

Source: https://github.com/isaqb-org/examination-foundation/blob/master/docs/mock_exam/Mock-Exam-Fragen-DE.pdf

The translation inverts the meaning of the sentence, leading to confusion with the given answer.

A correct translation (so the choice is incorrect) could be: "Die Einhaltung von DRY führt zu zusätzlichen Angriffsvektoren in der IT-Sicherheit."

**Comment by gernotstarke** [comment]
right you are.

see #43 and #42 - opened by @rhoadesre 

@Pharb - please comment on these issues too, another pair of watchful eyes on this question will help to improve it
(and too bad it's still in docx format, so we have no real change history...)

**Comment by gernotstarke** [comment]
I close this one, as it is covered in 42 and 43
