### ISSUE TITLE
unify filenames for mock-exam (DE, EN, ES etc)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#58]
currently file naming schema differs between DE/EN and ES

future names shall be mock-exam-questions-DE, mock-exam-questions-EN, mock-exam-questions-ES

and mock-exam-answers-DE, mock-exam-answers-EN, mock-exam-answers-ES

**Comment by gernotstarke** [comment]
seems to me that this is fixed, isn't it? @programming-wolf ?

**Comment by programming-wolf** [comment]
Yes, this has been fixed with the conversion to asciidoc. 
We have to adjust the Spanish version manually, but I'll take care of that tomorrow, since it will break the links on the overview page and iSAQB.org

**Comment by programming-wolf** [comment]
Fixed with e32cc90a0a61f9146c0783e2c277c20cbc199140
