### ISSUE TITLE
try out a conversion from docx to a merge-friendly  format (asciidoc)

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#59]

**Comment by gernotstarke** [comment]
successfully completed!

**Comment by rhoadesre** [comment]
Just curious what you used to perform the conversion.

**Comment by gernotstarke** [comment]
Gradle

Dr. Gernot Starke
+49-177-7282570
***@***.***
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.

**Comment by programming-wolf** [comment]
I think Roger meant whether we used an automated way to migrated word to asciidoc. Which we didn't, it's manual work. 😃
