### ISSUE TITLE
DE-Version: Gendering "Architekt:in" wird nicht durchgängig verwendet

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#65]
I suggest to ALWAYS use the gendered form of "Architekt:in" throughout all questions/answers.

We did that in the foundation curriculum, and should definitely repeat that here!!

**Comment by gernotstarke** [comment]
the culprits:

* Q-3
* Q-9

**Comment by rhoadesre** [comment]
Fine with me. Does this work automagically with plural as well?
I assume that we won't do this with the English version, e.g., his/her

**Comment by programming-wolf** [comment]
Jap, plural is "Architekt:innen". I guess that the English version is already using "their"/"theirs"?
