### ISSUE TITLE
Q-39: negative formulation, should rephrase to be positive

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#68]
instead of choosing the two most difficult to measure properties, let's ask for the three that can be measured best.

**Comment by gernotstarke** [comment]
@rhoadesre would be nice if you could have a look at Q-39 to verify it has gotten better :-)

**Comment by gernotstarke** [comment]
(ahm - in the ascidoc version, I forgot to mention that)

**Comment by rhoadesre** [comment]
I changed the formulation slightly. The positive formulation works well.

**Comment by rhoadesre** [comment]
I also changed the statement regarding the number of correct answers.

**Comment by rhoadesre** [comment]
As to the content, I would question whether or not security can be reliably tested or not. I'm not an expert in this area, but aren't there quantitative metrics to measure security?

**Comment by gernotstarke** [comment]
Roger, there's no commit with your changes in the asciidoc branch...

**Comment by rhoadesre** [comment]
Patience. I'm still working on it. :-)

**Comment by rhoadesre** [comment]
Should be pushed and committed now. Let me know if I did this correctly.

**Comment by gernotstarke** [comment]
no, not pushed.

**Comment by gernotstarke** [comment]
hhm - you changed the number of answer-options to TWO, but it's supposed to be THREE!!

It was two with the negative formulation, therefore it has to be three now (with 5 options to select from).

**Comment by gernotstarke** [comment]
and - btw: IF we change to the TWO best fitting answers, we needed to change the number of {y} answers in the first column too.

I suggest to leave it with THREE required answers

**Comment by rhoadesre** [comment]
Now I'm really confused. The statement was "Select the TWO ... answers" and I thought I changed it to "Select the Three .. changes.". In my version, it states "Select the THREE answers". And there are three answers (in my version) marked with a "y". Very confusing.
