### ISSUE TITLE
Provide total number of max achievable points

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/examination-foundation#7]
At least the solution sheet (and probably the explanation page) should contain the total number of points for the sample exam questions. (currently 50).

When 3.000 students (low estimate) each spend 3 minutes on the senseless and error prone tasks of determining the number of total points, 150 hours of human lifetime are wasted each year.

As a service, the score to pass (30.0 points) should be included.

**Comment by gernotstarke** [comment]
done.
