### ISSUE TITLE
Mock Q19: Question unclear

### ISSUE THREAD

**Issue by diveflo** [isaqb-org/examination-foundation#71]
Hi,

the wording of question 19 is unclear regarding if one should check information that should be **contained** or **avoided**

> When documenting a building block of your software architecture, which information should be
contained in the black-box description and which information should be avoided?

**Comment by gernotstarke** [comment]
thanx for the comment. The core aspect is the difference between black- and white box representation/documentation of a building block.

Would it be better if we phrased the question as "which information is appropriate for a black-box description, and which is not appropriate"?

**Comment by diveflo** [comment]
I would actually just leave out the second part of the question, so something like:

> When documenting a building block of your software architecture, which information should be contained in the black-box description?

Just because this isn't a K-question but a P-question.

**Comment by gernotstarke** [comment]
that has been clarified in the asciidoc port already AND in the rev-6 pdf...  (we released a number of silent updates in recent weeks). AsciiDoc is still in its own branch... check it out and build with ./gradlew

Text now reads:

`When documenting a building block of your software architecture, which information should the black-box description contain?`

I assume I can close this? Please verify :-)

**Comment by diveflo** [comment]
Ah - great! Sorry I missed that.
Yep we can close this now.
