### ISSUE TITLE
MockExam (DE): Q19 does not "duplicates" the number of correct answers in the text

### ISSUE THREAD

**Issue by janmaterne** [isaqb-org/examination-foundation#72]
While all other questions say in their text (and their header) how many correct answers are expected, question #19 (ID: Q-20-04-22) doesnt do that.

current: ... Welche Informationen sollten in seiner Black-Box-Beschreibung enthalten sein?
should: ... Welche zwei Informationen sollten in seiner Black-Box-Beschreibung enthalten sein?

This issue is related to issue #70 which discusses duplicating these numbers in header and text in general.

**Comment by gernotstarke** [comment]
right you are.
We're currently discussing if we shall remove that duplication in ALL questions, or leave it (as a potential convenience for some readers/users)

you got an opinion on that?

**Comment by gernotstarke** [comment]
(did you check out the asciidoc branch - which contains the most current update, not yet merged back into main...)

**Comment by janmaterne** [comment]
No I dont. I did the mock exam from the isaqb website and checked the doc file in the raw-folder.

While I could live with both options I prefer having the number in the text, because it is more prominent.

**Comment by janmaterne** [comment]
Checked the asciidoc branch. Not adressed there so I created a PR.
But regeneration of the pdf (de+en) plus updating the website would be still open.
And maybe other languages as asciidoc contains only de+en.

**Comment by programming-wolf** [comment]
Closed, Release 2021.2 contains the updated question.
