### ISSUE TITLE
Mock-exam, Q-37, improve answer option "log files"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#76]
suggestion from @feststelltaste

**Comment by gernotstarke** [comment]
I updated the score to 2 points, as we have four selections here...

**Comment by gernotstarke** [comment]
... @feststelltaste could you please elaborate what you mean by "improve answer option"? Otherwise, please close the issue

**Comment by feststelltaste** [comment]
I meant to improve / replace the answer option "logfiles", but it's good enough.
