### ISSUE TITLE
in download page (isaqb-org.github.io), append version-id and others to mock-exam

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/examination-foundation#78]
![image](https://user-images.githubusercontent.com/1233990/116815860-ccbb4580-ab5f-11eb-9b9d-736b60802b34.png)

**Comment by programming-wolf** [comment]
Fixed with isaqb-org/isaqb-org.github.io@d458bf2a1bb3df0dd3f9f7365dadad8c0ee98412
