### ISSUE TITLE
Versioning for released documents.

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/examination-foundation#8]
Currently the front page and the solutions do NOT contain a version number, only a publication date.

I STRONGLY recommend adding a version number to make it easier to refer to a specific version in case of updates (which will happen for sure),  to identify outdated versions and to keep all the different language Versions consistent.

I propose the following format, which we intend to use for other documents that will be published in several languages:

**{year}.{version}-{lang}-rev{revision}** 

So we have started with 2020.1-EN-rev0

Therefore typos that only occur in one language can be fixed (update rev) without changing the version to indicate that the content is still identical. We can also keep track of the translation status.

**Comment by gernotstarke** [comment]
right you are. Fixed
