### ISSUE TITLE
Beispielprüfung richtige Antwort zu Querschnittskonzepten weniger generalistisch

### ISSUE THREAD

**Issue by aburghacc** [isaqb-org/examination-foundation#87]
Antwort c auf Frage Q-17-13-01 "Welche Aussagen zu Querschnittskonzepten sind am zutreffendsten?" 
   _Eine einheitliche Ausnahmebehandlung wird **am einfachsten** erreicht, wenn die
Architekt:innen mit den Entwickler:innen vor der Implementierung ein geeignetes
Konzept vereinbaren._
erscheint ähnlich generalistisch (und damit zweifelhaft), wie d - für jedes Ziel ein Konzept.
Vorschlag: etwas abschwächen, zum Beispiel

Eine einheitliche Ausnahmebehandlung **kann man gut erreichen, indem** die
Architekt:innen mit den Entwickler:innen vor der Implementierung ein geeignetes Konzept vereinbaren.
FYI @gernotstarke

**Comment by gernotstarke** [comment]
included this proposal. Thanx
