### ISSUE TITLE
Initiate and curate a change log for the English version

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/examination-foundation#9]
As all translations will be derived from the English version. We should keep a curated change log or version history to make it easier for translators to keep track of changes. 

Yes, this is additional work (quite a bit of it). On the other hand it will save translators a lot of time, enables faster releases of translations and much easier quality assurance than having to diff full versions manually.

**Comment by gernotstarke** [comment]
done. Filename "changelog.md" in root directory.

I did not find a way to automatically INCLUDE its content in the readme.md, though... (sigh)

**Comment by programming-wolf** [comment]
I do not see that `changelog.md`? Did you push it?

**Comment by alxlo** [comment]
Neither do I :-)

**Comment by programming-wolf** [comment]
You can find it here, for the mock exam: https://github.com/isaqb-org/examination-foundation/tree/master/raw/mock_exam 

It is automatically rendered as Readme in that directory.
