### ISSUE TITLE
Q23 ist a question about the blackboard pattern which is now R3

### ISSUE THREAD

**Issue by pkutschera** [isaqb-org/examination-foundation#90]
My suggestion is to remove the question and instead include a new one in the mock exam.

**Comment by gernotstarke** [comment]
thanx @pkutschera for your suggestion.

The FL-WorkingGroup is really open for suggestions for such a new question...

(a pull-request would be welcome, but suggestions in a comment within this thread will be fine too...)

**Comment by pkutschera** [comment]
Suggestion: Für welche Art von Anwendungen kann das Muster Pipes-And-Filters eingesetzt werden:
(a) Anwendungen mit Echtzeitanforderungen
(b) Compiler
(c) User Interface
(d) Sicherheitskritische Anwendungen

**Comment by gernotstarke** [comment]
Wenn Du mir jetzt noch sagst, was Du davon für richtig hälst? Und wie Du bei den anderen begründest, dass ich das nicht einsetzen kann...

Du schreibst "kann"... und gibst keine weitere Einschränkung vor. Das macht Distraktoren sehr sehr schwierig.

Aus meiner Sicht alle ausser (a), und selbst da "kann" ich das nutzen...

**Comment by pkutschera** [comment]
Das stimmt. Meine Idee war eine richtige Antwort (b). Dann muss man die Frage so formulieren: Für welche Art von Anwendungen wird das Muster Pipes-And-Filters am Häufigsten eingesetzt. Um die Antwort noch eindeutiger zu machen, wäre es vielleicht auch sinnvoll (c) Groupware-Lösungen statt User Interface zu verwenden.

Oder aber man fragt nach den drei besten Lösungen und belässt es bei den obigen Antworten.

Was meinst du?

**Comment by gernotstarke** [comment]
"am häufigsten" finde ich auch eine sehr problematische Formulierung - weil Du damit den Anspruch erhebst, statistisch relevante Daten zu kennen...

Ich habe P&F übrigens oftmals in Batch-Systemen (mit sicherheitskritischen Daten...) eingesetzt - und Compiler arbeiten meiner Ansicht nach heute mit ganz anderen Mustern (inkrementell, mit Caching von ASTs, Delta- und on-the-fly Ersetzung von AST-Teilen und so... also nix P&F)

**Comment by pkutschera** [comment]
Wäre dies eine Möglichkeit?

Frage: Bei dem Proxy-Pattern (Stellvertreter Entwurfsmuster) handelt es sich
[] (a) um ein Erzeugungsmuster
[X] (b) um ein Strukturmuster
[] (c) um ein Verhaltensmuster

**Comment by gernotstarke** [comment]
Proxy selbst ist R3 (also auch schon nicht optimal, siehe Thema dieses Threads)

Die Differenzierung der Entwurfsmuster ist nicht Bestandteil des Lehrplans (und aus meiner persönlichen Sicht für Architekt:innen auch völlig irrelevant) - daher schon wieder ein "njet".

Sorry dass ich so erbsenzählerisch rüberkomme.

**Comment by pkutschera** [comment]
Gernot, das passt schon. Das hatte ich tatsächlich übersehen.

Neuer Versuch.
Frage:  Bei Pipes-and-Filters handelt es sich
[] (a) um ein Entwurfsmuster
[X] (b) um ein Architekturmuster
[] (c) um ein Entwurfsprinzip

**Comment by gernotstarke** [comment]
Peter - wie genau definierst Du den Unterschied zwischen a und b? Die Unterscheidung findet sich im Lehrplan auch nicht so wirklich - da ist in LZ 2-5 von "Lösungsmustern" die Rede.

Ich fände es gut, nach der architektonischen Relevanz oder möglichen Anwendungsfällen für P&F zu fragen - und nicht
auf so banale Formalia zu achten.

Also vielleicht "Welche Art von Problemen können durch Anwendung von P&F effizient/performant/flexibel gelöst werden?

**Comment by pkutschera** [comment]
"Welche Art von Problemen können durch Anwendung von P&F effizient/performant/flexibel gelöst werden?
[    ] (a) Echtzeitanforderungen
[ X ] (b) Kommandozeilen-basierte Anwendungen
[ X ] (c) Batches

Was meinst du?

**Comment by alxlo** [comment]
@pkutschera Das bewegt sich schon in eine ganz gute Richtung :-) 

Um daraus eine wirklich gute Prüfungsfrage zu machen, schlage ich vor, das noch etwas präziser zu fassen, da ja die Antworten (b und c sind Kategorien von Systemen, a ist eine Kategorie von Anforderungen) noch nicht ganz zur Frage ("Welche Arten von Problemen ...") passt. Sorry for being Krümelkacker, Prüfungsfragen sind wirklich "tricky".

Davon abgesehen sind Echtzeitsysteme auch nicht offensichtlich raus. P&F wird häufig für die digitale Signalverarbeitung eingesetzt, z. B. Software Defined Radio. Da gibt es schon Echtzeitanforderungen, nur dass P&F nicht direkt deren Probleme adressiert (Scheduling, Priorisierung, garantierte Antwortzeiten, ...) sondern nur indirekt zu deren Lösung beiträgt (z. B. Parallelisierung ermöglicht).

**Vorschlag:**

Für welche Entwurfsprobleme bietet das P&F-Pattern Lösungsansätze? Wählen Sie die zwei zutreffenden Antworten.

[  ]  (a) Verwaltung von Global State
[X] (b) Strukturierung von IT-Systemen die Datenströme verarbeiten
[X] (c) Entkopplung von Verarbeitungsschritten
[  ] (d) Entkopplung von zeitlichen Abhängigkeiten

**Comment by gernotstarke** [comment]
da bin ich bei euch. So ist das eine schöne Frage...
(fast zu schade für die Beispielprüfung...)

**Comment by pkutschera** [comment]
Das ist eine klasse Idee.

**Comment by gernotstarke** [comment]
@pkutschera, machst Du einen PR, bitte? wäre super ...

**Comment by pkutschera** [comment]
sehr gerne, ist erstellt.

**Comment by programming-wolf** [comment]
Erledigt mit ed7de94da8459b6a1098947fb0d1b431e41414b6
